#!/usr/bin/env node
// Generate the root composition (index.html) from src/timing.js (+ src/audio-plan.js)
// for one cut, plus build/timeline-<label>.json for BOTH cuts (audio build input).
//   node scripts/build_roots.mjs                 -> index.html = "compact" (20.00 s, default)
//   node scripts/build_roots.mjs --variant full  -> index.html = "full" (VO at natural pace)
// HyperFrames wants exactly one root entry, so the cut is switched by regenerating.
import fs from "node:fs";
import path from "node:path";
import vm from "node:vm";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const ctx = { window: {}, console };
vm.createContext(ctx);
for (const f of ["src/timing.js", "src/audio-plan.js"]) {
  const p = path.join(root, f);
  if (fs.existsSync(p)) vm.runInContext(fs.readFileSync(p, "utf8"), ctx, { filename: f });
}
const REEL = ctx.window.REEL;
const f3 = (x) => (Math.round(x * 1000) / 1000).toFixed(3);
const VO_CHAIN = JSON.stringify({
  version: 1,
  nodes: [
    { type: "highpass", id: "n1", label: "Remove Rumble", params: { frequency: 100, q: 0.707, poles: "2" } },
    { type: "compressor", id: "n2", label: "Even Out Levels", params: { threshold: -28, ratio: 3, attack: 8, release: 140, knee: 6, makeup: 3, mix: 1 } },
    { type: "gain", id: "n3", label: "Voice Level", params: { gain: 10 } },
    { type: "limiter", id: "n4", label: "Peak Ceiling", params: { limit: -2, attack: 1, release: 80, level_out: 0 } },
  ],
}).replace(/"/g, "&quot;");

const SCENES = [
  ["scene-01-intro", "s1"],
  ["scene-02-gathering", "s2"],
  ["scene-03-space-tech", "s3"],
  ["scene-04-challenge", "s4"],
  ["scene-05-website", "s5"],
  ["scene-06-final", "s6"],
];

function rootHtml(variant) {
  const T = REEL.timing.get(variant);
  const label = REEL.TIMING_DATA.variants[variant].label;
  const dur = f3(T.duration);
  const hosts = SCENES.map(([id, short], i) => {
    const s = T.scenes[id];
    return `      <div id="el-${short}" class="scene-host" data-composition-id="${id}" data-composition-src="compositions/${id}.html"
        data-start="${f3(s.hostStart)}" data-duration="${f3(s.hostDuration)}" data-track-index="${i + 1}" style="z-index:${10 + i}"></div>`;
  }).join("\n");

  // one clip per VO segment (cut at the take's natural pauses); rate 1 in the full cut
  const voFile = REEL.TIMING_DATA.vo.file;
  const vo = T.segs
    .map(
      (s, i) =>
        `      <audio id="vo-${s.id}" data-audio-group="voiceover" src="${voFile}" data-start="${f3(s.start)}" data-duration="${f3(s.duration)}" data-media-start="${f3(s.voStart)}"${s.rate === 1 ? "" : ` data-playback-rate="${s.rate.toFixed(4)}"`} data-fade-in="0.012" data-fade-out="0.025" data-volume="1" data-track-index="${20 + (i % 2)}"></audio>`
    )
    .join("\n");
  const plan = REEL.audioPlan ? REEL.audioPlan.mix : { music: 0.5, sfx: 0.7 };
  return `<!doctype html>
<!--
  GENERATED by scripts/build_roots.mjs from src/timing.js — do not edit by hand.
  Variant: ${variant} (${label}) · ${dur}s · 1080x1920 · 30fps
  Scenes live in compositions/, shared code in src/, media in assets/.
-->
<html lang="ar">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=1080, height=1920" />
    <title>Space Conference Reel · ${label}</title>
    <script>window.REEL_VARIANT = "${variant}";</script>
    <script src="assets/vendor/gsap.min.js"></script>
    <script src="assets/vendor/d3-array.min.js"></script>
    <script src="assets/vendor/d3-geo.min.js"></script>
    <script src="assets/data/geo.js"></script>
    <script src="src/utils/prng.js"></script>
    <script src="src/utils/anim.js"></script>
    <script src="src/timing.js"></script>
    <script src="src/components/earth.js"></script>
    <script src="src/components/satellite.js"></script>
    <script src="src/components/iraq-flag.js"></script>
    <link rel="stylesheet" href="src/styles/tokens.css" />
    <link rel="stylesheet" href="src/styles/typography.css" />
    <style>
      @font-face {
        font-family: "DIN Next LT Arabic";
        src: url("assets/fonts/DINNextLTArabic-Regular.ttf") format("truetype");
        font-weight: 400;
        font-style: normal;
        font-display: block;
      }
      html, body { margin: 0; background: #02040a; }
      #root { position: relative; width: 100%; height: 100%; overflow: hidden; background: #02040a; font-family: "DIN Next LT Arabic", sans-serif; }
      #root > .scene-host { position: absolute; inset: 0; }
    </style>
  </head>
  <body>
    <div id="root" data-composition-id="main" data-start="0" data-width="1080" data-height="1920" data-duration="${dur}" data-fps="30">
      <div id="el-bg" class="scene-host" data-composition-id="bg-space" data-composition-src="compositions/bg-space.html"
        data-start="0" data-duration="${dur}" data-track-index="0" style="z-index:0"></div>
${hosts}
      <div id="el-fx" class="scene-host" data-composition-id="fx-overlay" data-composition-src="compositions/fx-overlay.html"
        data-start="0" data-duration="${dur}" data-track-index="9" style="z-index:100"></div>

      <!-- Voice-over: the ElevenLabs take (assets/audio/voiceover.wav), never modified
           on disk — clips are cut at its natural pauses. The bus applies a transparent
           broadcast chain (rumble cut, gentle compression, level, peak ceiling) so the
           voice sits well above the score. -->
      <hf-audio-group id="voiceover" data-label="Voiceover" data-volume="${plan.vo === undefined ? 1 : plan.vo}"
        data-fx-chain="${VO_CHAIN}"></hf-audio-group>
${vo}
      <!-- Score: original music bed + sound design, generated by scripts/build_audio.py -->
      <audio id="music-bed" data-audio-group="music" src="assets/audio/music-${label}.wav" data-start="0" data-duration="${dur}" data-volume="${plan.music}" data-track-index="30"></audio>
      <audio id="sfx-stem" data-audio-group="sfx" src="assets/audio/sfx-${label}.wav" data-start="0" data-duration="${dur}" data-volume="${plan.sfx}" data-track-index="31"></audio>
    </div>
    <script>
      window.__timelines["main"] = gsap.timeline({ paused: true });
    </script>
  </body>
</html>
`;
}

fs.mkdirSync(path.join(root, "build"), { recursive: true });
const argv = process.argv.slice(2);
const want = argv.includes("--variant") ? argv[argv.indexOf("--variant") + 1] : "compact";
if (!REEL.TIMING_DATA.variants[want]) throw new Error("unknown variant " + want);
for (const variant of Object.keys(REEL.TIMING_DATA.variants)) {
  const T = REEL.timing.get(variant);
  const label = REEL.TIMING_DATA.variants[variant].label;
  const timeline = {
    variant, label, duration: T.duration, rate: T.rate,
    scenes: T.scenes, boundaries: T.boundaries, segs: T.segs,
    cues: Object.fromEntries(Object.keys(REEL.TIMING_DATA.words).concat(["lockup"]).map((k) => [k, T.cue(k)])),
    events: REEL.audioPlan ? REEL.audioPlan.resolve(T) : [],
  };
  fs.writeFileSync(path.join(root, "build", `timeline-${label}.json`), JSON.stringify(timeline, null, 1));
  if (variant === want) {
    fs.writeFileSync(path.join(root, "index.html"), rootHtml(variant));
    console.log(`index.html <- ${variant} (${label}): ${T.duration}s, VO rate ${T.rate.toFixed(4)}, ${timeline.events.length} audio events`);
  }
}
