#!/usr/bin/env node
// Bake Natural Earth data (world-atlas, public domain) into a small browser file
// so the Earth globe needs no network fetch at render time.
//   node scripts/build_geo.mjs
// Writes assets/data/geo.js -> window.REEL_GEO = { land, iraq, baghdad }
// and copies the d3-geo / d3-array UMD builds into assets/vendor/.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { feature } from "topojson-client";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const nm = (p) => path.join(root, "node_modules", p);
const read = (p) => JSON.parse(fs.readFileSync(nm(p), "utf8"));

const land50 = read("world-atlas/land-110m.json");
const countries50 = read("world-atlas/countries-50m.json");

// Round to STEP degrees (~1.5 px at globe scale), drop repeated points and
// islands smaller than MIN_PTS vertices — keeps the file small and per-frame
// projection cheap while the coastline still reads cleanly.
const STEP = 0.2, MIN_PTS = 6;
const q = (v) => Math.round(v / STEP) * STEP;
function ring(r) {
  const out = [];
  for (const [x, y] of r) {
    const p = [+q(x).toFixed(2), +q(y).toFixed(2)];
    const last = out[out.length - 1];
    if (!last || last[0] !== p[0] || last[1] !== p[1]) out.push(p);
  }
  if (out.length > 1) {
    const a = out[0], b = out[out.length - 1];
    if (a[0] !== b[0] || a[1] !== b[1]) out.push([a[0], a[1]]);
  }
  return out;
}
function roundGeom(g, minPts = MIN_PTS) {
  const polys = g.type === "Polygon" ? [g.coordinates] : g.coordinates;
  const kept = polys
    .map((poly) => poly.map(ring).filter((r, i) => r.length >= (i === 0 ? minPts : 6)))
    .filter((poly) => poly.length && poly[0].length >= minPts);
  return { type: "MultiPolygon", coordinates: kept };
}
const land = feature(land50, land50.objects.land);
const landOut = { type: "FeatureCollection", features: land.features.map((f) => ({ type: "Feature", properties: {}, geometry: roundGeom(f.geometry) })) };

const countries = feature(countries50, countries50.objects.countries);
const iraqF = countries.features.find((f) => String(f.id) === "368" || (f.properties && f.properties.name === "Iraq"));
if (!iraqF) throw new Error("Iraq not found in countries-50m");
const iraq = { type: "Feature", properties: { name: "Iraq" }, geometry: roundGeom(iraqF.geometry, 4) };

const out = `/* Generated by scripts/build_geo.mjs from world-atlas (Natural Earth, public domain). */
window.REEL_GEO = ${JSON.stringify({ land: landOut, iraq, baghdad: [44.366, 33.315] })};
`;
fs.mkdirSync(path.join(root, "assets", "data"), { recursive: true });
fs.writeFileSync(path.join(root, "assets", "data", "geo.js"), out);
fs.copyFileSync(nm("d3-array/dist/d3-array.min.js"), path.join(root, "assets", "vendor", "d3-array.min.js"));
fs.copyFileSync(nm("d3-geo/dist/d3-geo.min.js"), path.join(root, "assets", "vendor", "d3-geo.min.js"));
console.log("geo.js", (out.length / 1024).toFixed(1), "KB");
